### ISSUE TITLE
pipインストール時に依存モジュールを解決できない

### ISSUE THREAD

**Issue by hisuie08** [AttoCat/jmapy#12]
Windows10 64bit
Python3.8.3
pip 21.0.1

```
> python -m pip install git+https://github.com/AttoCat/jmapy

WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: C:\Users\astra\AppData\Local\Programs\Python\Python38-32\Include\UNKNOWN
sysconfig: C:\Users\astra\AppData\Local\Programs\Python\Python38-32\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting git+https://github.com/AttoCat/jmapy
  Cloning https://github.com/AttoCat/jmapy to c:\users\astra\appdata\local\temp\pip-req-build-hk9t7w5i
  Running command git clone -q https://github.com/AttoCat/jmapy 'C:\Users\astra\AppData\Local\Temp\pip-req-build-hk9t7w5i'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\astra\AppData\Local\Programs\Python\Python38-32\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\astra\\AppData\\Local\\Temp\\pip-req-build-hk9t7w5i\\setup.py'"'"'; __file__='"'"'C:\\Users\\astra\\AppData\\Local\\Temp\\pip-req-build-hk9t7w5i\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\astra\AppData\Local\Temp\pip-pip-egg-info-nru34h1d'
         cwd: C:\Users\astra\AppData\Local\Temp\pip-req-build-hk9t7w5i\
    Complete output (35 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\astra\AppData\Local\Temp\pip-req-build-hk9t7w5i\setup.py", line 3, in <module>
        setup()
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 121, in setup
        dist.parse_config_files()
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 699, in parse_config_files
        parse_configuration(self, self.command_options,
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\config.py", line 120, in parse_configuration
        meta.parse()
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\config.py", line 425, in parse
        section_parser_method(section_options)
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\config.py", line 398, in parse_section
        self[name] = value
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\config.py", line 183, in __setitem__
        value = parser(value)
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\config.py", line 513, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\config.py", line 348, in _parse_attr
        module = import_module(module_name)
      File "C:\Users\astra\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\astra\AppData\Local\Temp\pip-req-build-hk9t7w5i\jmapy\__init__.py", line 1, in <module>
        from .forecast import get_forecast
      File "C:\Users\astra\AppData\Local\Temp\pip-req-build-hk9t7w5i\jmapy\forecast.py", line 7, in <module>
        from dacite import Config, from_dict
    ModuleNotFoundError: No module named 'dacite'
    ----------------------------------------
WARNING: Discarding git+https://github.com/AttoCat/jmapy. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by hisuie08** [comment]
daciteモジュールとhumpsモジュールで怒られていたようなので両モジュールを手動で入れたあとリトライ
```
>pip install git+https://github.com/AttoCat/jmapy
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: c:\users\astra\appdata\local\programs\python\python38-32\Include\UNKNOWN
sysconfig: c:\users\astra\appdata\local\programs\python\python38-32\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting git+https://github.com/AttoCat/jmapy
  Cloning https://github.com/AttoCat/jmapy to c:\users\astra\appdata\local\temp\pip-req-build-hka8dv9y
  Running command git clone -q https://github.com/AttoCat/jmapy 'C:\Users\astra\AppData\Local\Temp\pip-req-build-hka8dv9y'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\astra\appdata\local\programs\python\python38-32\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\astra\\AppData\\Local\\Temp\\pip-req-build-hka8dv9y\\setup.py'"'"'; __file__='"'"'C:\\Users\\astra\\AppData\\Local\\Temp\\pip-req-build-hka8dv9y\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\astra\AppData\Local\Temp\pip-pip-egg-info-_m8fcfay'
         cwd: C:\Users\astra\AppData\Local\Temp\pip-req-build-hka8dv9y\
    Complete output (35 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\astra\AppData\Local\Temp\pip-req-build-hka8dv9y\setup.py", line 3, in <module>
        setup()
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 121, in setup
        dist.parse_config_files()
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\dist.py", line 699, in parse_config_files
        parse_configuration(self, self.command_options,
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\config.py", line 120, in parse_configuration
        meta.parse()
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\config.py", line 425, in parse
        section_parser_method(section_options)
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\config.py", line 398, in parse_section
        self[name] = value
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\config.py", line 183, in __setitem__
        value = parser(value)
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\config.py", line 513, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\config.py", line 348, in _parse_attr
        module = import_module(module_name)
      File "c:\users\astra\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\astra\AppData\Local\Temp\pip-req-build-hka8dv9y\jmapy\__init__.py", line 1, in <module>
        from .forecast import get_forecast
      File "C:\Users\astra\AppData\Local\Temp\pip-req-build-hka8dv9y\jmapy\forecast.py", line 8, in <module>
        from humps import decamelize
    ImportError: cannot import name 'decamelize' from 'humps' (c:\users\astra\appdata\local\programs\python\python38-32\lib\site-packages\humps\__init__.py)
    ----------------------------------------
WARNING: Discarding git+https://github.com/AttoCat/jmapy. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

どうやらモジュール足りないだけではないみたい

**Comment by AttoCat** [comment]
同様の環境で検証しましたが、再現できませんでした…

**Comment by AttoCat** [comment]
手動でインストールしたdaciteとpyhumpsのバージョンはいくつですか？

**Comment by hisuie08** [comment]
dacite-1.6.0
humps-0.2.2
ですね

**Comment by hisuie08** [comment]
`pip install setuptools --upgrade`
で再試行したところ正常にインストールできました！
